OCAMLC := ocamlc
OCAMLOPT := ocamlopt
OCAMLMKLIB := ocamlmklib
OCAMLFIND := ocamlfind
OCAMLDOC := ocamldoc
OCAMLC_WHERE := $(shell ocamlc -where)
CXX := g++ -fPIC
INC_IRRLICHT := /usr/include/irrlicht
LINK_LIB := -lIrrlicht
LD_DIR := /usr/lib
LD_PATH := -L$(LD_DIR)
DOC_DIR := ./doc/


lib: irrlicht.cma
opt: irrlicht.cmxa

.PHONY: lib opt


ML_FILES := \
 irr_core.ml \
 irr_base.ml \
 irr_video.ml \
 irr_gui.ml \
 irr_io.ml \
 irr_scene.ml \
 irr.ml

CMO_FILES := $(patsubst %.ml, %.cmo, $(ML_FILES))
CMX_FILES := $(patsubst %.ml, %.cmx, $(ML_FILES))


OBJS := \
 irr_base_wrap.o \
 irr_scene_wrap.o \
 irr_core_wrap.o \
 irr_gui_wrap.o \
 irr_io_wrap.o \
 irr_video_wrap.o \
 irr_wrap.o \
 irr_enums_wrap.o \
 utils.o

ENUMS_GEN := \
 irr_enums.mli \
 irr_enums_wrap_values.h \
 irr_enums_poly_values.txt \
 irr_enums_wrap_conv.cpp \
 irr_enums_wrap_conv.h


./hash_values/main.byte:
	make -C hash_values/

methods_hash_values.h: methods_hash_values.txt ./hash_values/main.byte
	./hash_values/main.byte methods_hash_values.txt > methods_hash_values.h

irr_enums_wrap_poly_values.h: irr_enums_poly_values.txt ./hash_values/main.byte
	./hash_values/main.byte irr_enums_poly_values.txt > irr_enums_wrap_poly_values.h

./enums/main.byte:
	make -C enums/

$(ENUMS_GEN): irr_enums.txt ./enums/main.byte
	./enums/main.byte

%.cmi: %.mli
	$(OCAMLC) -c $<

%.cmo: %.ml
	$(OCAMLC) -c $<

%.cmx: %.ml
	$(OCAMLOPT) -c $<

%.o: %.cpp
	$(CXX) -o $@ -I$(OCAMLC_WHERE) -c -I$(INC_IRRLICHT) $<

dllirrlicht_stubs.so: $(OBJS)
	$(OCAMLMKLIB) -oc irrlicht_stubs $^ \
	    $(LD_PATH) $(LINK_LIB)

irrlicht.cmxa:  $(CMX_FILES)  dllirrlicht_stubs.so
	$(OCAMLOPT) -a -o $@  $(CMX_FILES)  -cclib -lirrlicht_stubs \
	    -ccopt $(LD_PATH) \
	    -cclib $(LINK_LIB)

irrlicht.cma:  $(CMO_FILES)  dllirrlicht_stubs.so
	$(OCAMLC) -a -o $@  $(CMO_FILES)  -dllib -lirrlicht_stubs \
	    -ccopt $(LD_PATH) \
	    -cclib $(LINK_LIB)

install:
	$(OCAMLFIND) install irrlicht META *.cma *.cmxa *.cmi *.mli *.so *.a

uninstall:
	$(OCAMLFIND) remove irrlicht

clean:
	$(RM) *.[oa] *.so *.cm[ixoa] *.cmx[as]
	$(MAKE) -C hash_values/ clean
	$(MAKE) -C enums/ clean

.PHONY: doc clean_doc
doc:
	mkdir -p $(DOC_DIR)
	$(OCAMLDOC) $(MLI_FILES) \
	  irr_enums.mli \
	  irr_core.mli \
	  irr_video.mli \
	  irr_io.mli \
	  irr_gui.mli \
	  irr_scene.mli \
	  irr_base.mli \
	  irr.mli \
          -colorize-code -html \
          -d $(DOC_DIR)

clean_doc:
	$(RM) $(DOC_DIR)/*
	$(RM) -r $(DOC_DIR)



# Generated by `ocamldep *.ml *.mli`

irr.cmo : irr_video.cmi irr_scene.cmi irr_io.cmi irr_gui.cmi irr_enums.cmi \
    irr_core.cmi irr_base.cmi irr.cmi
irr.cmx : irr_video.cmx irr_scene.cmx irr_io.cmx irr_gui.cmx irr_enums.cmi \
    irr_core.cmx irr_base.cmx irr.cmi
irr.cmi : irr_video.cmi irr_scene.cmi irr_io.cmi irr_gui.cmi irr_enums.cmi \
    irr_base.cmi
irr_base.cmo : irr_enums.cmi irr_base.cmi
irr_base.cmx : irr_enums.cmi irr_base.cmi
irr_base.cmi : irr_enums.cmi
irr_core.cmo : irr_core.cmi
irr_core.cmx : irr_core.cmi
irr_core.cmi :
irr_enums.cmi :
irr_gui.cmo : irr_video.cmi irr_enums.cmi irr_core.cmi irr_base.cmi \
    irr_gui.cmi
irr_gui.cmx : irr_video.cmx irr_enums.cmi irr_core.cmx irr_base.cmx \
    irr_gui.cmi
irr_gui.cmi : irr_video.cmi irr_enums.cmi irr_core.cmi irr_base.cmi
irr_io.cmo : irr_enums.cmi irr_base.cmi irr_io.cmi
irr_io.cmx : irr_enums.cmi irr_base.cmx irr_io.cmi
irr_io.cmi : irr_enums.cmi irr_base.cmi
irr_scene.cmo : irr_video.cmi irr_enums.cmi irr_core.cmi irr_base.cmi \
    irr_scene.cmi
irr_scene.cmx : irr_video.cmx irr_enums.cmi irr_core.cmx irr_base.cmx \
    irr_scene.cmi
irr_scene.cmi : irr_video.cmi irr_enums.cmi irr_core.cmi irr_base.cmi
irr_video.cmo : irr_enums.cmi irr_core.cmi irr_base.cmi irr_video.cmi
irr_video.cmx : irr_enums.cmi irr_core.cmx irr_base.cmx irr_video.cmi
irr_video.cmi : irr_enums.cmi irr_core.cmi irr_base.cmi



# Generated by `g++ -MM  *.cpp *.h`

irr_base_wrap.o: irr_base_wrap.cpp irr_base_wrap.h global.h utils.h \
 methods_hash_values.h irr_enums_wrap.h irr_enums_wrap_values.h \
 irr_enums_wrap_poly_values.h irr_enums_wrap_conv.h irr_core_wrap.h \
 irr_video_wrap.h
irr_core_wrap.o: irr_core_wrap.cpp irr_core_wrap.h global.h utils.h \
 methods_hash_values.h irr_enums_wrap.h irr_enums_wrap_values.h \
 irr_enums_wrap_poly_values.h irr_enums_wrap_conv.h irr_base_wrap.h \
 irr_video_wrap.h
irr_enums_wrap_conv.o: irr_enums_wrap_conv.cpp
irr_enums_wrap.o: irr_enums_wrap.cpp global.h utils.h \
 methods_hash_values.h irr_enums_wrap.h irr_enums_wrap_values.h \
 irr_enums_wrap_poly_values.h irr_enums_wrap_conv.h irr_base_wrap.h \
 irr_core_wrap.h irr_video_wrap.h irr_enums_wrap_conv.cpp
irr_gui_wrap.o: irr_gui_wrap.cpp global.h utils.h methods_hash_values.h \
 irr_enums_wrap.h irr_enums_wrap_values.h irr_enums_wrap_poly_values.h \
 irr_enums_wrap_conv.h irr_base_wrap.h irr_core_wrap.h irr_video_wrap.h
irr_io_wrap.o: irr_io_wrap.cpp global.h utils.h methods_hash_values.h \
 irr_enums_wrap.h irr_enums_wrap_values.h irr_enums_wrap_poly_values.h \
 irr_enums_wrap_conv.h irr_base_wrap.h irr_core_wrap.h irr_video_wrap.h
irr_scene_wrap.o: irr_scene_wrap.cpp global.h utils.h \
 methods_hash_values.h irr_enums_wrap.h irr_enums_wrap_values.h \
 irr_enums_wrap_poly_values.h irr_enums_wrap_conv.h irr_base_wrap.h \
 irr_core_wrap.h irr_video_wrap.h
irr_wrap.o: irr_wrap.cpp global.h utils.h methods_hash_values.h \
 irr_enums_wrap.h irr_enums_wrap_values.h irr_enums_wrap_poly_values.h \
 irr_enums_wrap_conv.h irr_base_wrap.h irr_core_wrap.h irr_video_wrap.h
utils.o: utils.cpp global.h utils.h methods_hash_values.h \
 irr_enums_wrap.h irr_enums_wrap_values.h irr_enums_wrap_poly_values.h \
 irr_enums_wrap_conv.h irr_base_wrap.h irr_core_wrap.h irr_video_wrap.h
global.o: global.h utils.h methods_hash_values.h irr_enums_wrap.h \
 global.h irr_enums_wrap_values.h irr_enums_wrap_poly_values.h \
 irr_enums_wrap_conv.h irr_base_wrap.h irr_core_wrap.h irr_video_wrap.h
irr_base_wrap.o: irr_base_wrap.h global.h utils.h methods_hash_values.h \
 irr_enums_wrap.h irr_enums_wrap_values.h irr_enums_wrap_poly_values.h \
 irr_enums_wrap_conv.h irr_base_wrap.h irr_core_wrap.h irr_video_wrap.h
irr_core_wrap.o: irr_core_wrap.h global.h utils.h methods_hash_values.h \
 irr_enums_wrap.h irr_enums_wrap_values.h irr_enums_wrap_poly_values.h \
 irr_enums_wrap_conv.h irr_base_wrap.h irr_core_wrap.h irr_video_wrap.h
irr_enums_wrap_conv.o: irr_enums_wrap_conv.h
irr_enums_wrap.o: irr_enums_wrap.h global.h utils.h methods_hash_values.h \
 irr_enums_wrap.h irr_base_wrap.h irr_core_wrap.h irr_video_wrap.h \
 irr_enums_wrap_values.h irr_enums_wrap_poly_values.h \
 irr_enums_wrap_conv.h
irr_enums_wrap_poly_values.o: irr_enums_wrap_poly_values.h
irr_enums_wrap_values.o: irr_enums_wrap_values.h
irr_video_wrap.o: irr_video_wrap.h global.h utils.h methods_hash_values.h \
 irr_enums_wrap.h irr_enums_wrap_values.h irr_enums_wrap_poly_values.h \
 irr_enums_wrap_conv.h irr_base_wrap.h irr_core_wrap.h irr_video_wrap.h
methods_hash_values.o: methods_hash_values.h
utils.o: utils.h

